/*
 * Copyright (c) 2010-2026 SaumilP. Apache License 2.0.
 */
package io.github.saumilp.starters.s3.config;

import org.springframework.boot.context.properties.ConfigurationProperties;

/**
 * Configuration properties for the AWS S3 starter, bound from the
 * {@code spring.aws.s3.*} namespace.
 *
 * <p>Example configuration for AWS production:
 * <pre>{@code
 * spring:
 *   aws:
 *     s3:
 *       region: eu-west-1
 *       access-key-id: ${AWS_ACCESS_KEY_ID}
 *       secret-access-key: ${AWS_SECRET_ACCESS_KEY}
 *       default-bucket: my-app-uploads
 * }</pre>
 *
 * <p>Example configuration for LocalStack:
 * <pre>{@code
 * spring:
 *   aws:
 *     s3:
 *       endpoint-override: http://localhost:4566
 *       path-style-access: true
 *       region: us-east-1
 *       access-key-id: test
 *       secret-access-key: test
 * }</pre>
 *
 * @since 1.0.0
 */
@ConfigurationProperties(prefix = "spring.aws.s3")
public class S3ConfigurationProperties {

    /** Creates an instance with default values. */
    public S3ConfigurationProperties() {
    }

    /** Whether the S3 starter is enabled. Defaults to {@code true}. */
    private boolean enabled = true;

    /**
     * AWS region for the S3 client. Defaults to {@code "us-east-1"}.
     * Override with the region where your bucket resides.
     */
    private String region = "us-east-1";

    /**
     * AWS access key ID for static credential configuration.
     * Leave blank to use the default AWS credential provider chain
     * (environment variables, instance profile, etc.).
     */
    private String accessKeyId = "";

    /**
     * AWS secret access key paired with {@link #accessKeyId}.
     * Leave blank to use the default AWS credential provider chain.
     */
    private String secretAccessKey = "";

    /**
     * Custom endpoint URL for S3-compatible services such as LocalStack or MinIO.
     * Leave blank to use the standard AWS S3 endpoints.
     * Example: {@code http://localhost:4566}
     */
    private String endpointOverride = "";

    /**
     * Whether to use path-style access for S3 requests ({@code http://endpoint/bucket/key})
     * instead of virtual-hosted-style ({@code http://bucket.endpoint/key}).
     * Must be {@code true} for LocalStack and MinIO compatibility.
     * Defaults to {@code false}.
     */
    private boolean pathStyleAccess = false;

    /**
     * Default bucket name used by application-level convenience wrappers.
     * Not used internally by the starter — purely for injection into application beans.
     * Defaults to empty string.
     */
    private String defaultBucket = "";

    /**
     * Expiry duration in minutes for pre-signed GET URLs generated by
     * {@link io.github.saumilp.starters.s3.service.S3StorageService#presignedGetUrl}.
     * Defaults to {@code 60} minutes.
     */
    private long presignedUrlExpiryMinutes = 60L;

    /**
     * Returns whether the S3 starter is enabled.
     * @return {@code true} if enabled
     */
    public boolean isEnabled() { return enabled; }

    /**
     * Sets whether the starter is enabled.
     *
     * @param enabled {@code false} to disable auto-configuration entirely
     */
    public void setEnabled(boolean enabled) { this.enabled = enabled; }

    /**
     * Returns the AWS region.
     * @return the region; never {@code null}
     */
    public String getRegion() { return region; }

    /**
     * Sets the AWS region.
     *
     * @param region the AWS region code; must not be {@code null}
     */
    public void setRegion(String region) { this.region = region; }

    /**
     * Returns the static AWS access key ID.
     * @return the access key ID; empty string means use credential chain
     */
    public String getAccessKeyId() { return accessKeyId; }

    /**
     * Sets the static AWS access key ID.
     *
     * @param accessKeyId the AWS access key ID
     */
    public void setAccessKeyId(String accessKeyId) { this.accessKeyId = accessKeyId; }

    /**
     * Returns the static AWS secret access key.
     * @return the secret key; empty string means use credential chain
     */
    public String getSecretAccessKey() { return secretAccessKey; }

    /**
     * Sets the static AWS secret access key.
     *
     * @param secretAccessKey the AWS secret access key
     */
    public void setSecretAccessKey(String secretAccessKey) { this.secretAccessKey = secretAccessKey; }

    /**
     * Returns the custom endpoint override URL, or empty string for the default AWS endpoint.
     * @return the endpoint override; never {@code null}
     */
    public String getEndpointOverride() { return endpointOverride; }

    /**
     * Sets the custom endpoint override URL.
     *
     * @param endpointOverride the custom endpoint URL; empty string to use AWS default
     */
    public void setEndpointOverride(String endpointOverride) { this.endpointOverride = endpointOverride; }

    /**
     * Returns whether path-style S3 access is enabled.
     * @return {@code true} if path-style access is forced
     */
    public boolean isPathStyleAccess() { return pathStyleAccess; }

    /**
     * Sets whether path-style S3 access is used.
     *
     * @param pathStyleAccess {@code true} for LocalStack / MinIO compatibility
     */
    public void setPathStyleAccess(boolean pathStyleAccess) { this.pathStyleAccess = pathStyleAccess; }

    /**
     * Returns the default bucket name.
     * @return the default bucket; may be empty
     */
    public String getDefaultBucket() { return defaultBucket; }

    /**
     * Sets the default bucket name.
     *
     * @param defaultBucket the default bucket name
     */
    public void setDefaultBucket(String defaultBucket) { this.defaultBucket = defaultBucket; }

    /**
     * Returns the pre-signed URL expiry in minutes.
     * @return the expiry duration; always positive
     */
    public long getPresignedUrlExpiryMinutes() { return presignedUrlExpiryMinutes; }

    /**
     * Sets the pre-signed URL expiry in minutes.
     *
     * @param presignedUrlExpiryMinutes the expiry in minutes; must be positive
     */
    public void setPresignedUrlExpiryMinutes(long presignedUrlExpiryMinutes) {
        this.presignedUrlExpiryMinutes = presignedUrlExpiryMinutes;
    }
}
