/*
 * Copyright (c) 2010-2026 SaumilP. Apache License 2.0.
 */
package io.github.saumilp.starters.outbox.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;

import java.time.Instant;
import java.util.UUID;

/**
 * JPA entity representing a single event in the transactional outbox table.
 *
 * <p>Domain services persist {@code OutboxEvent} rows atomically within the same database
 * transaction as the business state change. The
 * {@link io.github.saumilp.starters.outbox.relay.OutboxEventRelay} subsequently polls for
 * {@link OutboxEventStatus#PENDING} events and forwards them to the configured message broker.
 *
 * <p>The consumer is responsible for creating the {@code outbox_events} table — see the
 * README for the recommended Flyway migration script.
 *
 * @since 1.0.0
 */
@Entity
@Table(name = "outbox_events")
public class OutboxEvent {

    /** Creates an empty outbox event (required by JPA). */
    public OutboxEvent() {
    }

    /** Surrogate UUID primary key, generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /**
     * The domain aggregate type that produced this event (e.g., {@code "Order"}).
     * Used by consumers to route events to the correct handler.
     */
    @Column(name = "aggregate_type", nullable = false, length = 100)
    private String aggregateType;

    /**
     * The identifier of the specific aggregate instance (e.g., the order ID as a string).
     * Used as the Kafka partition key to guarantee ordering per aggregate.
     */
    @Column(name = "aggregate_id", nullable = false, length = 255)
    private String aggregateId;

    /**
     * The event type name in upper-snake-case (e.g., {@code "ORDER_CREATED"}).
     * Maps to the Kafka topic suffix or RabbitMQ routing key.
     */
    @Column(name = "event_type", nullable = false, length = 100)
    private String eventType;

    /** The JSON-serialised event payload. */
    @Column(name = "payload", nullable = false, columnDefinition = "TEXT")
    private String payload;

    /** UTC instant at which the event was persisted. Set automatically by {@link #onCreate()}. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** UTC instant at which the event was successfully forwarded to the broker. {@code null} until processed. */
    @Column(name = "processed_at")
    private Instant processedAt;

    /** Current lifecycle status of the event. */
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    private OutboxEventStatus status;

    /** Number of relay attempts made so far. Incremented on each failure. */
    @Column(name = "retry_count", nullable = false)
    private int retryCount = 0;

    /** The exception message from the last failed relay attempt; {@code null} on initial persist. */
    @Column(name = "error_message", columnDefinition = "TEXT")
    private String errorMessage;

    /**
     * JPA lifecycle callback — sets {@link #createdAt} and initialises {@link #status} to
     * {@link OutboxEventStatus#PENDING} before the first database insert.
     */
    @PrePersist
    protected void onCreate() {
        createdAt = Instant.now();
        status    = OutboxEventStatus.PENDING;
    }

    // -------------------------------------------------------------------------
    // Getters and setters
    // -------------------------------------------------------------------------

    /**
     * Returns the surrogate primary key.
     *
     * @return the UUID primary key; {@code null} before the entity is persisted
     */
    public UUID getId() { return id; }

    /**
     * Returns the domain aggregate type.
     *
     * @return the aggregate type label; never {@code null} after construction
     */
    public String getAggregateType() { return aggregateType; }

    /**
     * Sets the domain aggregate type.
     *
     * @param aggregateType the aggregate type; must not be {@code null} or blank
     */
    public void setAggregateType(String aggregateType) { this.aggregateType = aggregateType; }

    /**
     * Returns the aggregate instance identifier.
     *
     * @return the aggregate ID; never {@code null} after construction
     */
    public String getAggregateId() { return aggregateId; }

    /**
     * Sets the aggregate instance identifier.
     *
     * @param aggregateId the aggregate ID; must not be {@code null} or blank
     */
    public void setAggregateId(String aggregateId) { this.aggregateId = aggregateId; }

    /**
     * Returns the event type name.
     *
     * @return the event type; never {@code null} after construction
     */
    public String getEventType() { return eventType; }

    /**
     * Sets the event type name.
     *
     * @param eventType the event type in upper-snake-case; must not be {@code null}
     */
    public void setEventType(String eventType) { this.eventType = eventType; }

    /**
     * Returns the JSON-serialised event payload.
     *
     * @return the payload; never {@code null} after construction
     */
    public String getPayload() { return payload; }

    /**
     * Sets the JSON-serialised event payload.
     *
     * @param payload the payload string; must not be {@code null}
     */
    public void setPayload(String payload) { this.payload = payload; }

    /**
     * Returns the instant at which the event was persisted.
     *
     * @return the creation instant; set by {@link #onCreate()}
     */
    public Instant getCreatedAt() { return createdAt; }

    /**
     * Sets the instant at which the event was persisted.
     *
     * <p>Normally populated automatically by the {@link #onCreate()} JPA lifecycle callback;
     * exposed as a setter primarily to support constructing fixtures in tests.
     *
     * @param createdAt the creation instant
     */
    public void setCreatedAt(Instant createdAt) { this.createdAt = createdAt; }

    /**
     * Returns the instant at which the event was successfully relayed to the broker.
     *
     * @return the processing instant; {@code null} until processed
     */
    public Instant getProcessedAt() { return processedAt; }

    /**
     * Sets the instant at which the event was successfully relayed.
     *
     * @param processedAt the processing instant
     */
    public void setProcessedAt(Instant processedAt) { this.processedAt = processedAt; }

    /**
     * Returns the current lifecycle status of the event.
     *
     * @return the status; never {@code null} after initial persist
     */
    public OutboxEventStatus getStatus() { return status; }

    /**
     * Sets the lifecycle status.
     *
     * @param status the new status; must not be {@code null}
     */
    public void setStatus(OutboxEventStatus status) { this.status = status; }

    /**
     * Returns the number of relay attempts made so far.
     *
     * @return the retry count; always non-negative
     */
    public int getRetryCount() { return retryCount; }

    /**
     * Sets the retry count.
     *
     * @param retryCount the new retry count; must be non-negative
     */
    public void setRetryCount(int retryCount) { this.retryCount = retryCount; }

    /**
     * Returns the error message from the last failed relay attempt.
     *
     * @return the error message; {@code null} if no failure has occurred
     */
    public String getErrorMessage() { return errorMessage; }

    /**
     * Sets the error message from the last failed relay attempt.
     *
     * @param errorMessage the exception message from the broker adapter
     */
    public void setErrorMessage(String errorMessage) { this.errorMessage = errorMessage; }
}
